services:
  hpp-fastapi:
    image: kouzmigo/fastapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  hpp-streamlit:
    image: kouzmigo/streamlit
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    environment:
      API_URL: http://hpp-fastapi:8000
